export const currentOpeningsData = [
  {
    position: "PHP Team Lead",
    shortDetail:
      "If you think you can do team management & you have good knowledge of PHP, apply now. ",
    experience: "4+",
    jobType: "Full-Time",
    location: "Ahmedabad",
    openings: 1,
    link: "php-team-lead",
    jobDescription:
      "The role includes overseeing and guiding a team of PHP developers in the development and maintenance of PHP-based web applications and systems. This role combines technical expertise in PHP programming with leadership and project management skills.",
    minimumQualification: "B.E/B.Tech/M.E/M.Tech in CS or IT/ BCA/ MCA",
    roles: [
      "Preferred candidate should be confident and should have willingness to undertake multiple challenges and should have strong desire to emerge as winner in handling crucial situations.",
      "Should be capable of handling multiple projects.",
      "Should have a good knowledge and experience of Ajax, jQuery, WordPress, Core PHP, Laravel, Shopify etc.",
      "Should be efficient enough to utilize the resources available to him.",
      "Analyze client requirements and prepare scope of work and time frame accordingly.",
      "Can handle and plan project milestones and deadlines.",
      "Should be able to interact with client during entire project development life cycle.",
    ],
    responsibility: [
      "Should have excellent communication and leadership skills.",
      "Should have good analytical and problem-solving skills.",
      "Knowledge of open source ecommerce softwares.",
      "Ability to motivate staff in a team-oriented, collaborative environment.",
      "Should be eager to learn new things and take up challenges.",
      "Self-learn and career-oriented.",
      "Enthusiastic, energetic, detail-oriented, and self-motivated.",
      "Should be able to interact with clients during the entire project development life cycle and manage project delivery on time.",
      "Should be able to improve the technical competence of the team through training development of existing and new team members.",
      "Must be productive, self-disciplined, and capable of managing team productivity and result-oriented work quality.",
    ],
  },
  {
    position: "Laravel Developer",
    shortDetail:
      "We’re hiring developers who specialize in the Laravel framework & also have core PHP concepts clear.",
    experience: "2 to 4",
    jobType: "Full-Time",
    location: "Ahmedabad",
    openings: 1,
    link: "laravel-developer",
    jobDescription:
      "As a Laravel developer, the primary role involves designing, developing, and maintaining web applications using Laravel's features and conventions, however one should be flexible to work with any PHP based CMS/framework.",
    minimumQualification: "BE, ME, MCA or MSC (IT)",
    roles: [
      "Preferred candidate should be confident and should have willingness to undertake multiple challenges and should have strong desire to emerge as winner in handling crucial situations.",
      "Should be capable of handling multiple projects.",
      "Should have a good knowledge and experience of Ajax, jQuery, WordPress, Core PHP, Laravel, Shopify etc.",
      "Should be efficient enough to utilize the resources available to him.",
      "Analyze client requirements and prepare scope of work and time frame accordingly.",
      "Can handle and plan project milestones and deadlines.",
      "Should be able to interact with client during entire project development life cycle.",
    ],
    responsibility: [
      "Should have excellent communication and leadership skills.",
      "Should have good analytical and problem-solving skills.",
      "Knowledge of open source ecommerce softwares.",
      "Ability to motivate staff in a team-oriented, collaborative environment.",
      "Should be eager to learn new things and take up challenges.",
      "Self-learn and career-oriented.",
      "Enthusiastic, energetic, detail-oriented, and self-motivated.",
      "Should be able to interact with clients during the entire project development life cycle and manage project delivery on time.",
      "Should be able to improve the technical competence of the team through training development of existing and new team members.",
      "Must be productive, self-disciplined, and capable of managing team productivity and result-oriented work quality.",
    ],
  },
  {
    position: "React js Developer",
    shortDetail:
      "Looking for developers proficient in React.js with a passion for building user-friendly web interfaces.",
    experience: "1+",
    jobType: "Full-Time",
    location: "Ahmedabad",
    openings: 5,
    link: "react-js-developer",
    jobDescription:
      "The React.js Developer will be responsible for designing and developing dynamic user interfaces for web applications using the React.js framework.",
    minimumQualification: "B.E/B.Tech/MCA or equivalent",
    roles: [
      "Develop user interfaces with modern JavaScript frameworks, libraries, and tools, particularly React.js.",
      "Collaborate with the design team to translate UI/UX design wireframes into high-quality code.",
      "Ensure the technical feasibility of UI/UX designs and optimize components for maximum performance.",
      "Participate in code reviews and contribute to best practices and coding standards.",
    ],
    responsibility: [
      "Work closely with other developers to ensure consistency across the front-end.",
      "Ensure applications are compatible across multiple platforms and browsers.",
      "Stay up-to-date with emerging technologies in front-end development.",
      "Continuously improve the performance and user experience of the application.",
      "Troubleshoot and resolve issues as they arise.",
    ],
  },
  {
    position: "Node js Developer",
    shortDetail:
      "We’re hiring skilled Node.js developers to build and maintain server-side applications.",
    experience: "4+",
    jobType: "Full-Time",
    location: "Ahmedabad",
    openings: 2,
    link: "node-js-developer",
    jobDescription:
      "The Node.js Developer will be responsible for developing and maintaining server-side components, working on the backend of web applications, and ensuring seamless data flow.",
    minimumQualification: "B.E/B.Tech/MCA or equivalent",
    roles: [
      "Develop server-side applications using Node.js and associated frameworks.",
      "Work with front-end developers to integrate user-facing elements with server-side logic.",
      "Write reusable, testable, and efficient code.",
      "Implement security and data protection measures.",
    ],
    responsibility: [
      "Ensure the scalability and reliability of applications.",
      "Maintain code quality through code reviews and unit testing.",
      "Collaborate with cross-functional teams to define and deliver new features.",
      "Optimize applications for performance and scalability.",
      "Stay current with industry trends and implement best practices in development.",
    ],
  },
];
