export const Designation = [
    { value: "Frontend Developer", label: "Frontend Developer", id: "Frontend Developer" },
    { value: "Backend Developer", label: "Backend Developer", id: "Backend Developer" },
    { value: "Full Stack Developer", label: "Full Stack Developer", id: "Full Stack Developer" },
    { value: "DevOps Engineer", label: "DevOps Engineer", id: "DevOps Engineer" },
    { value: "Data Scientist", label: "Data Scientist", id: "Data Scientist" },
    { value: "Data Analyst", label: "Data Analyst", id: "Data Analyst" },
    { value: "Machine Learning Engineer", label: "Machine Learning Engineer", id: "Machine Learning Engineer" },
    { value: "Cloud Engineer", label: "Cloud Engineer", id: "Cloud Engineer" },
    { value: "Systems Administrator", label: "Systems Administrator", id: "Systems Administrator" },
    { value: "Cybersecurity Specialist", label: "Cybersecurity Specialist", id: "Cybersecurity Specialist" },
    { value: "Network Engineer", label: "Network Engineer", id: "Network Engineer" },
    { value: "Software Engineer", label: "Software Engineer", id: "Software Engineer" },
    { value: "Mobile App Developer", label: "Mobile App Developer", id: "Mobile App Developer" },
    { value: "Database Administrator", label: "Database Administrator", id: "Database Administrator" },
    { value: "UX/UI Designer", label: "UX/UI Designer", id: "UX/UI Designer" },
    { value: "Product Manager", label: "Product Manager", id: "Product Manager" },
    { value: "Technical Support Engineer", label: "Technical Support Engineer", id: "Technical Support Engineer" },
    { value: "IT Project Manager", label: "IT Project Manager", id: "IT Project Manager" },
    { value: "QA Engineer", label: "QA Engineer", id: "QA Engineer" },
    { value: "Scrum Master", label: "Scrum Master", id: "Scrum Master" },
    { value: "Software Architect", label: "Software Architect", id: "Software Architect" },
    { value: "Business Analyst", label: "Business Analyst", id: "Business Analyst" },
    { value: "IT Consultant", label: "IT Consultant", id: "IT Consultant" },
    { value: "Blockchain Developer", label: "Blockchain Developer", id: "Blockchain Developer" },
    { value: "AI Specialist", label: "AI Specialist", id: "AI Specialist" },
    { value: "VR/AR Developer", label: "VR/AR Developer", id: "VR/AR Developer" },
    { value: "Game Developer", label: "Game Developer", id: "Game Developer" },
    { value: "Embedded Systems Engineer", label: "Embedded Systems Engineer", id: "Embedded Systems Engineer" },
    { value: "Technical Writer", label: "Technical Writer", id: "Technical Writer" },
    { value: "IT Auditor", label: "IT Auditor", id: "IT Auditor" }
]
