import NavBar from "@/components/Navbar";
import { Poppins } from '@next/font/google';
import "../styles/globals.scss";
import "./layout.scss";
import dynamic from "next/dynamic";
import localFont from 'next/font/local';

const BottomFooter = dynamic(() => import("@/components/BottomFooter/Bottomfooter"));

const poppins = Poppins({
    subsets: ['latin'],
    weight: ['400', '500', '700'], // Add the weights you need
    variable: '--font-poppins', // This creates a CSS variable
});

const avenirRegular = localFont({
    src: '/fonts/AvenirNextWorld-Regular.ttf',
    variable: '--font-avenir-regular',
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" className={`${avenirRegular.variable} ${poppins.variable}`}>
            <head>
                <Script src="https://smtpjs.com/v3/smtp.js" strategy="afterInteractive" />
            </head>
            <body id="body" className="font-container">
                <NavBar />
                <div id="smooth-content">
                    <div className="main-wrapper">{children}</div>
                    <BottomFooter />
                </div>
                <VideoPlayerModel />
            </body>
        </html>
    );
}
